---
title: "ESM 206 Lab 10"
author: "Eva Wilson"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Attach packages:
library(tidyverse)
library(janitor)
library(usethis)

library(beepr)
library(praise)
library(cowsay)
library(paletteer)
library(sf)
```

## beepr::beep()

```{r}
beep()
beep(10)
```

Use `beep()` to give yourself an audio alert.

## for loop + beep 

```{r, eval = FALSE}
# write a sequence from 1-99
# wrap this in a reverse function (rev), such that it goes 99, 98, 97
for (i in rev(seq(1:9999))) {
  print(paste(i, "bottles of beer on the wall"))
}

# this let's you know when the code chunk has run
beep(4)
```

## praise 

```{r}
# caps will ensure your adjective is returned uppercase
praise("${EXCLAMATION}!!! This code works ${adverb_manner}!")

# your statement should follow this format

praise("Holy ${creating}, Batman - this code works ${ADVERB_MANNER}!")
```

## cowsay:: say to have characters say something

```{r}
say("I love chickpeas!", by = "frog") # julia
```

## usethis for everything 

### update your R profile 

```{r}
# coded in console, here for reference: usethis::edit_r_profile()
```

If you start from a non-version controlled R Project, then follow this workflow to establish a connection with GitHub:

R Project first, then git & GitHub repo. 

- usethis::use_git()
- usethis::use_github()

